### ISSUE TITLE
TFJob example pets-training.yaml problem

### ISSUE THREAD

**Issue by antigenius0910** [kubeflow/examples#204]
Hi,  

Thank you so much for all the examples, they looks great! 

I am following your example on object detection from below link
https://github.com/kubeflow/examples/blob/master/object_detection/submit_job.md

However, when I try to submit the example pets-training.yaml file, I see below errors.
```
ychuang@Kubernetes-master:~/mykubeflow-app/examples/object_detection/jobs$ kubectl apply -f pets-training.yaml 
error: unable to recognize "pets-training.yaml": no matches for kind "TFJob" in version "kubeflow.org/v1alpha2"
```
After some research on the forum I found the problem has been fixed on kubeflow.org/v1alpha1,
therefore I change pets-training.yaml from 

```
apiVersion: kubeflow.org/v1alpha2
```
to
```
apiVersion: kubeflow.org/v1alpha1
```

and the TFJob does got created. great.
```
ychuang@Kubernetes-master:~/mykubeflow-app/examples/object_detection/jobs$ kubectl apply -f pets-training.yaml 
tfjob.kubeflow.org/pets-training created
```

but then the submission fail due to below error.
```
ychuang@Kubernetes-master:~/mykubeflow-app/examples/object_detection/jobs$ kubectl describe tfjob.kubeflow.org/pets-training
Name:         pets-training
Namespace:    mykubeflow
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"kubeflow.org/v1alpha1","kind":"TFJob","metadata":{"annotations":{},"name":"pets-training","namespace":"mykubeflow"},"spec":{"tfReplicaSp...
API Version:  kubeflow.org/v1alpha1
Kind:         TFJob
Metadata:
  Creation Timestamp:  2018-07-27T21:10:12Z
  Generation:          1
  Resource Version:    1633409
  Self Link:           /apis/kubeflow.org/v1alpha1/namespaces/mykubeflow/tfjobs/pets-training
  UID:                 7339bb92-91e1-11e8-8ae8-0800279c6d84
Spec:
  Runtime Id:     
  Replica Specs:  <nil>
  Termination Policy:
    Chief:
      Replica Index:  0
      Replica Name:   MASTER
  Tf Image:           tensorflow/tensorflow:1.3.0
Status:
  Phase:             Failed
  Reason:            invalid job spec: Missing ReplicaSpec for chief: MASTER
  Replica Statuses:  <nil>
  State:             Failed
Events:              <none>
```

Can you help me to identify which part was wrong for the pets-training.yaml file?
Thanks. below is my pets-training.yaml from your example page.

```
---
apiVersion: kubeflow.org/v1alpha1
kind: TFJob
metadata:
  name: pets-training
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: lcastell/pets_object_detection
            imagePullPolicy: IfNotPresent
            workingDir: /models
            command:
              - "python"
              - "research/object_detection/train.py"
            args:
              - "--logtostderr"
              - "--pipeline_config_path=/pets_data/faster_rcnn_resnet101_pets.config"
              - "--train_dir=/pets_data/train"
            volumeMounts:
              - mountPath: "/pets_data"
                name: pets-data
          volumes:
            - name: pets-data
              persistentVolumeClaim:
                claimName: pets-data-claim
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: lcastell/pets_object_detection
            imagePullPolicy: IfNotPresent
            workingDir: /models
            command:
              - "python"
              - "research/object_detection/train.py"
            args:
              - "--logtostderr"
              - "--pipeline_config_path=/pets_data/faster_rcnn_resnet101_pets.config"
              - "--train_dir=/pets_data/train"
            volumeMounts:
              - mountPath: "/pets_data"
                name: pets-data
          volumes:
            - name: pets-data
              persistentVolumeClaim:
                claimName: pets-data-claim
~                                                                                                              
```
