### ISSUE TITLE
[mnist] Make it work with S3

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#466]
I'm updating the mnist example #465 to work with 0.4 and add tests (#460).

Creating this issue to track additional work needed to verify it works with S3 and perform follow on actions.

One piece that's needed is we need to update the ksonnet component to allow setting environment variables based on secret key references. For S3 we need the TFJob spec to look something like

```
 containers:
    env:
   - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: awsAccessKeyID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: awsSecretAccessKey
```

To support this we'd like a user to be able to do something like

```
ks param set secretKeyRefs=aws-creds.awsAccessKeyId,aws-creds.awsSecretAccessKey
```

This just requires a bit of jsonnet to correctly parse the parameters.
