### ISSUE TITLE
error: unable to recognize "kube/tfjob.yaml": no matches for kind "TFJob" in version "kubeflow.org/v1alpha1"

### ISSUE THREAD

**Issue by ali-raza-tariq** [kubeflow/examples#586]
Hi guys, i am trying to run mnist example from (https://github.com/learnk8s/distributed-tensorflow-on-k8s). I am running local bare-metal kubernetes cluster with kubernetes v1.14.3 & kubeflow v0.5.1 installed. When i try to create a tfjob, i receive this error 
```
error: unable to recognize "kube/tfjob.yaml": no matches for kind "TFJob" in version "kubeflow.org/v1alpha1"
``` 
When i checked using `kubectl api-versions`, i found 3 kubeflow versions installed.
```
kubeflow.org/v1alpha1
kubeflow.org/v1beta1
kubeflow.org/v1beta2
```
When i tried to change `v1alpha1` to `v1beta1` or `v1beta2`, i got the error (by executing `kubectl describe tfjob` - as tfjob fails) 
```
Type     Reason            Age   From         Message
  ----     ------            ----  ----         -------
  Warning  InvalidTFJobSpec  16s   tf-operator  Failed to marshal the object to TFJob; the spec is invalid: failed to marshal the object to TFJob
```
Upon searching online- i have found conflicting accounts of people saying alpha1 is out dated, others saying this was fixed for alpha1. Kindly provide some info about what is going on, which version should be used, what does this error means? 
p.s. when i run the documentation example in minikube using kubeflow v0.1.2 (in the link) - it works fine with api-version `v1alpha1`.

**Comment by jinchihe** [comment]
Hi @ali-raza-tariq That's caused by the tfjobs upgraded in the kubeflow 0.5.1 that's used in your cluster. Run below command to check the tfjobs version.

```
kubectl describe crd tfjobs.kubeflow.org
```
To work around the problem, you can update the `apiVersion` to `kubeflow.org/v1beta2` or  `kubeflow.org/v1` in your `kube/tfjob.yaml`, and try again.

**Comment by ali-raza-tariq** [comment]
Thanks for replying @jinchihe , i already tried kubeflow.org/v1beta2 and it gave me the same error. Upon executing the command, it says `v1beta1`. Below is the complete output
```
Name:         tfjobs.kubeflow.org
Namespace:
Labels:       app.kubernetes.io/deploy-manager=ksonnet
              ksonnet.io/component=tf-job-operator
Annotations:  ksonnet.io/managed:
                {"pristine":"H4sIAAAAAAAA/6STwW7bMAyG73sMnl0P2S6DbkWHAeuhC5qiOxQ50DbtqJFEgaKyDoHffZDtJguKoYf5JJLiR/MndQSM9pEkWQ5gikEvSqGYqd5/SbXlj4dVQ4orq...
              kubecfg.ksonnet.io/garbage-collect-tag: gc-tag
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2019-07-01T17:20:28Z
  Generation:          1
  Resource Version:    314235
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/tfjobs.kubeflow.org
  UID:                 855757f2-9c24-11e9-b5b1-e4115be7af98
Spec:
  Additional Printer Columns:
    JSON Path:  .status.conditions[-1:].type
    Name:       State
    Type:       string
    JSON Path:  .metadata.creationTimestamp
    Name:       Age
    Type:       date
  Conversion:
    Strategy:  None
  Group:       kubeflow.org
  Names:
    Kind:       TFJob
    List Kind:  TFJobList
    Plural:     tfjobs
    Singular:   tfjob
  Scope:        Namespaced
  Subresources:
    Status:
  Validation:
    openAPIV3Schema:
      Properties:
        Spec:
          Properties:
            Tf Replica Specs:
              Properties:
                Chief:
                  Properties:
                    Replicas:
                      Maximum:  1
                      Minimum:  1
                      Type:     integer
                PS:
                  Properties:
                    Replicas:
                      Minimum:  1
                      Type:     integer
                Worker:
                  Properties:
                    Replicas:
                      Minimum:  1
                      Type:     integer
  Version:                      v1beta1
  Versions:
    Name:     v1beta1
    Served:   true
    Storage:  true
    Name:     v1beta2
    Served:   true
    Storage:  false
Status:
  Accepted Names:
    Kind:       TFJob
    List Kind:  TFJobList
    Plural:     tfjobs
    Singular:   tfjob
  Conditions:
    Last Transition Time:  2019-07-01T17:20:28Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1beta1
Events:  <none>
```
Also when i tried to change it to only `kubeflow/v1`, i got the same old message for no matches found.
```
error: unable to recognize "kube/tfjob.yaml": no matches for kind "TFJob" in version "kubeflow.org/v1"
```

**Comment by ali-raza-tariq** [comment]
Hi guys, i figured out the problem. Apparently, the syntax has changed for defining the tfjob in the yaml file. As i mentioned, i was using kubeflow v0.1.2 tutorial example which had 'tfReplicaType' field to define the role of pods. But looking at the latest examples, they no longer that field rather mention the field value above the indented block. For anyone interested, here are both the original & updated versions
`Original`
```
apiVersion: kubeflow.org/v1alpha1
kind: TFJob
metadata:
  name: tfjob1
spec:
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          volumes:
            - name: nfs-volume
              persistentVolumeClaim:
                claimName: nfs
          containers:
            - name: tensorflow
              image: learnk8s/mnist:1.0.0
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
```
`Updated`
```
apiVersion: kubeflow.org/v1beta2
kind: TFJob
metadata:
  name: tfjob1
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          volumes:
            - name: nfs-volume
              persistentVolumeClaim:
                claimName: nfs
          containers:
            - name: tensorflow
              image: learnk8s/mnist:1.0.0
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
```
