### ISSUE TITLE
unable to build kustomize for mnist example

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/examples#681]
I'm trying to follow the [mnist example with the local storage steps](https://github.com/kubeflow/examples/tree/master/mnist#local-storage). I've tried to follow those steps but when I do `kustomize build .` then I get:
```
no matches for OriginalId kubeflow.org_v1beta2_TFJob|~X|$(trainingName); no matches for CurrentId kubeflow.org_v1beta2_TFJob|~X|$(trainingName); failed to find unique target for patch kubeflow.org_v1beta2_TFJob|$(trainingName
```
I've tried with kustomize v3 (`go get -u sigs.k8s.io/kustomize/kustomize/v3`) and v2 (`go get -u sigs.k8s.io/kustomize/kustomize/v2`) but I get the same error with both. I am running from the `training/local` directory (have also tried the GCS one and get the same error). 

I'm not able to get as far as https://github.com/kubeflow/examples/issues/672 as I can't get the `kustomize build .` step to complete.

**Comment by fenglixa** [comment]
kustomize 2.0.3 is required and mentioned in [minist example document](https://github.com/kubeflow/examples/tree/master/mnist)

Seems other version of kustomize has issues on it. I remember such issues was logged and closed before

**Comment by ryandawsonuk** [comment]
Oh I hadn't noticed that. But this time I tried with `go get sigs.k8s.io/kustomize/kustomize/v2@v2.0.3` but I get the same error. Actually it's a different error from the [one referenced in the doc](https://github.com/kubernetes-sigs/kustomize/issues/1295)

**Comment by ryandawsonuk** [comment]
I've tried to deduce what the kustomize should evaluate to and came up with this:
```
apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: mnist-train-local
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - name: tensorflow
            command:
            - /usr/bin/python
            - /opt/model.py
            - --tf-model-dir=/mnt
            - --tf-export-dir=/mnt/export
            - --tf-train-steps=200
            - --tf-batch-size=100
            - --tf-learning-rate=0.01
            env:
            - name: modelDir
              value: "/mnt"
            - name: exportDir
              value: "/mnt/export"
            - name: trainSteps
              value: "200"
            - name: batchSize
              value: "100"
            - name: learningRate
              value: "0.01"
            image: docker.io/ryandawsonuk/kftfmodel:0.0.1
            workingDir: /opt
            volumeMounts:
            - mountPath: "/mnt"
              name: local-storage
          volumes:
          - name: local-storage
            persistentVolumeClaim:
              claimName: seldon-mnist-tfjob-gslnf-modelpvc
          restartPolicy: OnFailure
      tfReplicaType: MASTER
```
It fails though with `IOError: [Errno socket error] [Errno 99] Cannot assign requested address` from
```
  File "/opt/model.py", line 174, in main
    mnist = tf.contrib.learn.datasets.DATASETS['mnist'](args.tf_data_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 300, in load_mnist
    return read_data_sets(train_dir)
```
I guess I'm getting a path or format wrong. Would you be able to share an example?

**Comment by fenglixa** [comment]
Here is the output(sucessful example) from myside after run "kustomize build ."
```
apiVersion: v1
data:
  batchSize: "100"
  exportDir: /mnt/export
  learningRate: "0.02"
  modelDir: /mnt
  name: tfjob-021
  pvcMountPath: /mnt
  pvcName: fengpvc
  trainSteps: "200"
kind: ConfigMap
metadata:
  name: mnist-map-training-4t25c985bg
---
apiVersion: kubeflow.org/v1beta2
kind: TFJob
metadata:
  name: tfjob-021
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - command:
            - /usr/bin/python
            - /opt/model.py
            - --tf-model-dir=$(modelDir)
            - --tf-export-dir=$(exportDir)
            - --tf-train-steps=$(trainSteps)
            - --tf-batch-size=$(batchSize)
            - --tf-learning-rate=$(learningRate)
            env:
            - name: modelDir
              value: /mnt
            - name: exportDir
              value: /mnt/export
            - name: trainSteps
              value: "200"
            - name: batchSize
              value: "100"
            - name: learningRate
              value: "0.02"
            image: docker.io/fenglixa/mytfmodel:tag
            name: tensorflow
            volumeMounts:
            - mountPath: /mnt
              name: local-storage
            workingDir: /opt
          restartPolicy: OnFailure
          volumes:
          - name: local-storage
            persistentVolumeClaim:
              claimName: fengpvc
    Ps:
      replicas: 1
      template:
        spec:
          containers:
          - command:
            - /usr/bin/python
            - /opt/model.py
            - --tf-model-dir=$(modelDir)
            - --tf-export-dir=$(exportDir)
            - --tf-train-steps=$(trainSteps)
            - --tf-batch-size=$(batchSize)
            - --tf-learning-rate=$(learningRate)
            env:
            - name: modelDir
              value: /mnt
            - name: exportDir
              value: /mnt/export
            - name: trainSteps
              value: "200"
            - name: batchSize
              value: "100"
            - name: learningRate
              value: "0.02"
            image: docker.io/fenglixa/mytfmodel:tag
            name: tensorflow
            volumeMounts:
            - mountPath: /mnt
              name: local-storage
            workingDir: /opt
          restartPolicy: OnFailure
          volumes:
          - name: local-storage
            persistentVolumeClaim:
              claimName: fengpvc
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - command:
            - /usr/bin/python
            - /opt/model.py
            - --tf-model-dir=$(modelDir)
            - --tf-export-dir=$(exportDir)
            - --tf-train-steps=$(trainSteps)
            - --tf-batch-size=$(batchSize)
            - --tf-learning-rate=$(learningRate)
            env:
            - name: modelDir
              value: /mnt
            - name: exportDir
              value: /mnt/export
            - name: trainSteps
              value: "200"
            - name: batchSize
              value: "100"
            - name: learningRate
              value: "0.02"
            image: docker.io/fenglixa/mytfmodel:tag
            name: tensorflow
            volumeMounts:
            - mountPath: /mnt
              name: local-storage
            workingDir: /opt
          restartPolicy: OnFailure
          volumes:
          - name: local-storage
            persistentVolumeClaim:
              claimName: fengpvc
```
