### ISSUE TITLE
[codelab-e2e-gis-feedback]: kfctl apply platform -V --> "No valid versions with the prefix \"1.11\" found."

### ISSUE THREAD

**Issue by tarrade** [kubeflow/examples#707]
I am doing this tutorial on GCP using CloudShell. I did some other tutorial before with Kubeflow.

I have some issue with the following step:
`kfctl apply platform -V`

this generate a YAML file and some option seems to be problematic:

```
- name: kubeflow
  properties:
    autoprovisioning-config:
      enabled: true
      max-accelerator:
      - count: 8
        type: nvidia-tesla-k80
      max-cpu: 20
      max-memory: 200
    cluster-version: "1.11"
```
and give the following ERROR:
```
ERRO[0043] Updating kubeflow-codelab error: &{Code:RESOURCE_ERROR Location:/deployments/kubeflow-codelab/resources/kubeflow-codelab Message:{"ResourceType":"gcp-types/container-v1beta1:projects.locations.clusters","
ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"No valid versions with the prefix \"1.11\" found."
```
I used 
`gcloud container get-server-config --zone us-central1-a`
to get the list of version and tried few of them like the one below (only 1.11.X)

`cluster-version: 1.11.2-gke.9`
and give a different issue that this master version is not supported

`kubeflow-codelab: {"ResourceType":"gcp-types/container-v1beta1:projects.locations.clusters","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Master version \"1.11.2-gke.9\" is unsupported.","status":"INVALID_ARGUMENT","statusMessage":"Bad`

It seems that on GCP 1.11.X is not available anymore:
https://cloud.google.com/kubernetes-engine/docs/release-notes

using: `cluster-version: 1.12.10-gke.22` fix the issue

I don't know which version of k8s is recommended in general for GCP, it will be nice to add a Warning that people may need to change this parameter in the YAML file. 
Thanks
