### ISSUE TITLE
mnist pipelines example "failed with exit code 2"

### ISSUE THREAD

**Issue by alforik** [kubeflow/examples#780]
**At mnist pipelines example**

my setting like follows
```
  platform = 'onprem' 
  model_export_dir='/mnt/export
  pvc_name='pvc-hostpath'
```
pv and pvc yaml is
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/k8s-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-hostpath
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: manual
```

**error logs**
pipeline stops in progress "serv" container
error logs like this
```
- This step is in Failed state with this message: failed with exit code 2

Deploying the model '/mnt/export'
Deploying mnist-service to the cluster mnist-pipeline
Cluster "mnist-pipeline" set.
User "pipeline" set.
Context "kubeflow" created.
Switched to context "kubeflow".
Initializing KSonnet app...
```
